### ISSUE TITLE
[Request] Add an option to select the orientation of the body render

### ISSUE THREAD

**Issue by ImRodry** [crafatar/crafatar#277] opened 2021-01-03 21:24 UTC
I use Crafatar to add a thumbnail to a command in my discord bot but, as you may know, discord puts thumbnails on the right side of the embed. Well seeing as the body render is always facing right, this looks quite odd so I'd like to request the addition of a new modifier called `orientation` which can have the values `left` or `right` (`right` by default) which would change the way the render faces. I couldn't understand the code where this is done as I've never worked with the canvas module, so that's why I'm creating this issue in hopes to get it added soon.

**Comment by jomo** [comment] 2021-01-03 21:26
Duplicate of #90

**Closed by jomo** 2021-01-03 21:26 UTC

**Comment by MisterFixx** [comment] 2021-01-03 21:56
I've implemented that for my service, https://mc-heads.net/#isometric a few months ago.

**Comment by McLive** [comment] 2021-01-03 22:05
Please leave a PR to solve #90 then :D

**Comment by MisterFixx** [comment] 2021-01-03 22:25
> Please leave a PR to solve #90 then :D

Doubt my PHP is gonna be any good to a node.js project.
