### ISSUE TITLE
3D Rendering of Capes on Body Render, Animation Option

### ISSUE THREAD

**Issue by McSlushie** [crafatar/crafatar#192] opened 2016-08-31 14:17 UTC
There should be some sort of option to show capes on body renders. That would be nice if you want to show off your cape or something. Also, most skin search website allow an option the make the player look like its moving or walking. Just thought it would be neat. Nice job though, I use this in a bunch of projects.

**Comment by jomo** [comment] 2016-08-31 15:10
Duplicate of #154.

I think animation is out of the scope of this project. Most other projects use client-side canvas or WebGL rendering (some using Crafatar as the source for the skin/cape file). We would have to fall back to bloated and ugly GIFs.

**Closed by jomo** 2016-08-31 15:10 UTC
Labels: duplicate
